#!/bin/bash
echo -e "\n\n\n\n\n\nConfigurando gitignore..."
echo -e "*~\n*main*c" >> .gitignore
git add .gitignore
git commit -m "Automatic .gitignore config"
git push -u origin master
echo upload starting, please witre what commit do you want?
read -p 'Commit: ' com
git add .
git commit -m $com
git push -u origin master
echo Successful upload, if any file is missing, use git add file
git status
